export { Button, buttonVariants } from '@/shared/ui/Button';
export { MainGrid } from '@/shared/ui/MainGrid';
export { BlockTitle } from '@/shared/ui/BlockTitle';
export { ProjectCard } from '@/shared/ui/ProjectCard';
export { BlockContainer } from '@/shared/ui/BlockContainer';
export { Label } from '@/shared/ui/Label';
export { Form } from '@/shared/ui/Form';
export { Input } from '@/shared/ui/Input';
export { Textarea } from '@/shared/ui/Textarea';
export { Socials } from '@/shared/ui/Socials';
export { DynamicLogo } from '@/shared/ui/DynamicLogo';
export { Spotlight } from '@/shared/ui/Spotlight';
export { LanguageSwitcher } from '@/shared/ui/LanguageSwitcher';
