// The app compiles src/assets/*.svg through @svgr/webpack, so every import is
// a React component. esbuild (both the DS bundle and the preview bundler) has
// no such loader and hands back a data URI, which React then treats as an
// element type — the whole subtree dies. These generated wrappers restore the
// svgr contract; .design-sync/tsconfig.sync.json aliases each import onto one.
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';

const SRC = 'src/assets';
const OUT = '.design-sync/svgr';
const names = [];
for (const f of readdirSync(SRC).filter((n) => n.endsWith('.svg'))) {
  const raw = readFileSync(join(SRC, f), 'utf8');
  const open = raw.match(/<svg\b[^>]*>/i);
  if (!open) throw new Error(`no <svg> root in ${f}`);
  const attrs = Object.fromEntries(
    [...open[0].matchAll(/([:\w-]+)\s*=\s*"([^"]*)"/g)].map((m) => [m[1], m[2]])
  );
  const inner = raw.slice(raw.indexOf(open[0]) + open[0].length, raw.lastIndexOf('</svg>'));
  const stem = basename(f, '.svg');
  const keep = ['viewBox', 'fill', 'stroke', 'stroke-width', 'xmlns'];
  const passthrough = keep
    .filter((k) => attrs[k] != null)
    .map((k) => `${k === 'stroke-width' ? 'strokeWidth' : k}=${JSON.stringify(attrs[k])}`)
    .join(' ');
  writeFileSync(
    join(OUT, `${stem}.tsx`),
    `// generated by .design-sync/scripts/gen-svgr.mjs from ${SRC}/${f} — do not edit\n` +
      `import type { SVGProps } from 'react';\n\n` +
      `const Svg = (props: SVGProps<SVGSVGElement>) => (\n` +
      `  <svg ${passthrough} width='1em' height='1em' {...props} dangerouslySetInnerHTML={{ __html: ${JSON.stringify(inner)} }} />\n` +
      `);\n\nexport default Svg;\n`
  );
  names.push(stem);
}
console.log(`wrote ${names.length} svgr wrapper(s): ${names.join(', ')}`);

// The paths plugin only understands exact keys and a single trailing `*`, so
// each svg needs its own entry, ordered before the `@/*` catch-all.
const paths = {};
for (const n of names) paths[`@/assets/${n}.svg`] = [`.design-sync/svgr/${n}.tsx`];
paths['next/image'] = ['.design-sync/shims/next-image.tsx'];
// The plugin's extension probe tries the bare stem first and existsSync() is
// true for a directory, so a barrel import like `@/components` would resolve
// to the directory itself and esbuild fails with "is a directory". Pin every
// directory import to its index file, ahead of the `@/*` catch-all.
for (const d of ['components', 'components/terminal', 'data/i18n', 'hooks', 'interfaces']) {
  paths[`@/${d}`] = [`src/${d}/index.ts`];
}
paths['@/*'] = ['src/*'];
writeFileSync(
  '.design-sync/tsconfig.sync.json',
  JSON.stringify({ compilerOptions: { baseUrl: '..', paths } }, null, 2) + '\n'
);
console.log('wrote .design-sync/tsconfig.sync.json');
